# Generated by Django 5.0.2 on 2024-02-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
