# Generated by Django 5.0.2 on 2024-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
